# kubectl subprocess needs to know how to connect to the eks server...?
#export KUBECONFIG=$HOME/eks/mgmt/mgmt-eks-a-cluster.kubeconfig
#alias kb-copy-token="kubectl create token admin-user -n kube-system | xclip -selection clipboard"

# a JSON Web Token created for the "josh" service account
# I used this to log in to the dashboard
# eyJhbGciOiJSUzI1NiIsImtpZCI6IldPbENwRFRyU29WVFlGbGVKdlV2NXROd1NIWThFeVlnYm13X0JjTXMwbkEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNjg5OTc3NzczLCJpYXQiOjE2ODk5NzQxNzMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6Impvc2giLCJ1aWQiOiJlZGUxODk5Zi03ZTgxLTQ3ZjAtOTQyOC1hZmU4NjFlYTc5N2IifX0sIm5iZiI6MTY4OTk3NDE3Mywic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6am9zaCJ9.PP58p5vBmb4qsCv3-171wuXdPQAKUVQM2DDI1fb4Hfm_ecc2Yn_BuZk0t0kxb8W1kDbxT5XR2u1qMMHXI-Q1zMqxWdbj6XMNkza6ZphTFFaqihhFBbxWgTkbrglyY8QXCUCaQvxDZ3qLxdb1SCt-wkVbrrEgeTHy1sXx1Cyuyh6xIwqw1poRC5AsSZLbSBIhCXQaVucTQlHO8u38ieIU2mihCuYRfbmhgNBtY4VEDZLngVemZvxatp6EMtCmtu_i8y2Z3L-kSJN4YA6qiLFLIVDuOxfVt_de1yhWyBSuE20TLWhXtvEwFIgut_FUvNkl09UYZO_6Jsuo4hIMfP6C7g
